apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
  namespace: keycloak
spec:
  instances: 1
  storage:
    size: 1Gi
  superuserSecret:
    name: keycloak-db-superuser
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      dataChecksums: true