apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: keycloak
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: "password"
  KC_DB: postgres
  KC_DB_URL: jdbc:postgresql://keycloak-db-rw/keycloak
  KC_DB_USERNAME: app_user
  KC_DB_PASSWORD: "app_password_for_keycloak"