apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: keycloak
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: "password"
  KC_DB: postgres
  KC_DB_URL: jdbc:postgresql://rust-api-db-rw.cnpg.svc.cluster.local/appdb
  KC_DB_USERNAME: postgres
  KC_DB_PASSWORD: postgres