apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-api
  namespace: myapp
  labels:
    app: rust-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-api
  template:
    metadata:
      labels:
        app: rust-api
    spec:
      containers:
      - name: rust-api
        image: registry.local:5000/rust_api:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: rust-api-app-secret
        env:
        - name: APP_HOST
          value: "0.0.0.0"
        - name: APP_PORT
          value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: rust-api-service
  namespace: myapp
  labels:
    app: rust-api
spec:
  selector:
    app: rust-api
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP