---
- name: Ensure base packages are installed
  apt:
    name:
      - curl
      - ca-certificates
      - gnupg
      - apt-transport-https
      - jq
      - python3
      - python3-apt
      - socat
      - iptables
      - ebtables
      - ethtool
    state: present
    update_cache: true

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb | int > 0
  changed_when: false

- name: Ensure swap is disabled in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*\sswap\s)'
    replace: '# \1'
  register: fstab_swap

- name: Ensure br_netfilter module is loaded
  modprobe:
    name: br_netfilter
    state: present

- name: Ensure br_netfilter loads on boot
  lineinfile:
    path: /etc/modules-load.d/k8s.conf
    line: br_netfilter
    create: yes
    state: present

- name: Configure sysctl for Kubernetes networking
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present
    reload: yes

- name: Configure sysctl for IPv6
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    state: present
    reload: yes

- name: Ensure registry.local resolves on the VM
  lineinfile:
    path: /etc/hosts
    regexp: '.*\sregistry\.local$'
    line: "{{ ansible_default_ipv4.address }} registry.local"
    state: present
