---
galaxy_info:
  author: Rust API Team
  description: K3s lightweight Kubernetes installation
  company: Local Development
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - kubernetes
    - k3s
    - container-orchestration

dependencies: []







